2025-08-14 14:25:23,480 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:483)
2025-08-14 14:25:50,078 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage CreateSnapshotRecordsStage (evaluator.py:125)
2025-08-14 14:25:50,136 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage PhysicalLayerUpdateStage (evaluator.py:125)
2025-08-14 14:25:50,146 - ThreadPoolExecutor-1_0 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema analytics.sqlmesh__sqlmesh_example (evaluator.py:361)
2025-08-14 14:25:50,147 - ThreadPoolExecutor-1_1 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema analytics.sqlmesh__analytics (evaluator.py:361)
2025-08-14 14:25:50,147 - ThreadPoolExecutor-1_2 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema analytics.sqlmesh__staging (evaluator.py:361)
2025-08-14 14:25:50,149 - ThreadPoolExecutor-1_3 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema analytics.sqlmesh__raw (evaluator.py:361)
2025-08-14 14:25:50,326 - ThreadPoolExecutor-1_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: e73fcb00b8654b46bdf6c0c86c520009 */ SELECT
  current_catalog (base.py:2260)
2025-08-14 14:25:50,408 - ThreadPoolExecutor-1_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: e73fcb00b8654b46bdf6c0c86c520009 */ SELECT
  current_catalog (base.py:2260)
2025-08-14 14:25:50,475 - ThreadPoolExecutor-1_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: e73fcb00b8654b46bdf6c0c86c520009 */ SELECT
  current_catalog (base.py:2260)
2025-08-14 14:25:50,634 - ThreadPoolExecutor-1_3 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: e73fcb00b8654b46bdf6c0c86c520009 */ SELECT
  current_catalog (base.py:2260)
2025-08-14 14:25:50,677 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage AuditOnlyRunStage (evaluator.py:125)
2025-08-14 14:25:50,705 - ThreadPoolExecutor-2_0 - sqlmesh.core.snapshot.evaluator - INFO - Auditing snapshot SnapshotId<"analytics"."sqlmesh_example"."full_model": 2070410384> (evaluator.py:553)
2025-08-14 14:25:50,778 - ThreadPoolExecutor-2_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: e73fcb00b8654b46bdf6c0c86c520009 */ SELECT
  "attname" AS "column_name",
  "pg_catalog".format_type("atttypid", "atttypmod") AS "data_type"
FROM "pg_catalog"."pg_attribute"
JOIN "pg_catalog"."pg_class"
  ON "pg_class"."oid" = "attrelid"
JOIN "pg_catalog"."pg_namespace"
  ON "pg_namespace"."oid" = "relnamespace"
WHERE
  (
    "attnum" > 0
    AND NOT "attisdropped"
    AND "relname" = 'sqlmesh_example__full_model__3968245968'
  )
  AND "nspname" = 'sqlmesh__sqlmesh_example' (base.py:2260)
2025-08-14 14:25:50,792 - MainThread - sqlmesh.core.scheduler - INFO - Execution failed for node ('"analytics"."sqlmesh_example"."full_model"', ((1754784000000, 1755043200000), 0)) (scheduler.py:499)
Traceback (most recent call last):
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 250, in _render
    transformed_expressions = ensure_list(macro_evaluator.transform(expression))
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 291, in transform
    transformed = exp.replace_tree(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 8616, in replace_tree
    new_node = fun(node)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 259, in evaluate_macros
    raise SQLMeshError(f"Macro variable '{node.name}' is undefined.")
sqlmesh.utils.errors.SQLMeshError: Macro variable 'columns' is undefined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 69, in _process_node
    self.fn(node)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/scheduler.py", line 443, in evaluate_node
    audit_results = self._audit_snapshot(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/scheduler.py", line 693, in _audit_snapshot
    audit_results = self.snapshot_evaluator.audit(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 569, in audit
    self._audit(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1137, in _audit
    query = snapshot.model.render_audit_query(audit, **kwargs)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/model/definition.py", line 529, in render_audit_query
    rendered_query = query_renderer.render(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 530, in render
    expressions = super()._render(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 252, in _render
    raise_config_error(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/utils/errors.py", line 200, in raise_config_error
    raise error_type(f"{msg} at '{location}'", location)
sqlmesh.utils.errors.ConfigError: Failed to resolve macros for

SELECT
  *
FROM @this_model
WHERE
  @AND(@REDUCE(@EACH(@columns, c -> c IS NULL), (l, r) -> l OR r), @condition)

Macro variable 'columns' is undefined.
 at '.'

The above exception was the direct cause of the following exception:

sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node ('"analytics"."sqlmesh_example"."full_model"', ((1754784000000, 1755043200000), 0))
2025-08-14 14:25:50,873 - MainThread - sqlmesh.core.context - INFO - Plan application failed. (context.py:1702)
Traceback (most recent call last):
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 1694, in apply
    self._apply(plan, circuit_breaker)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 2487, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 107, in evaluate
    self._evaluate_stages(plan_stages, plan)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 127, in _evaluate_stages
    handler(stage, plan)
  File "/mnt/c/Users/josh/venv/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 276, in visit_audit_only_run_stage
    raise PlanError("Plan application failed.")
sqlmesh.utils.errors.PlanError: Plan application failed.
2025-08-14 14:25:50,878 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
